from coc_time.schemas import Inversion, InversionManager

_inversions = [
    Inversion(concept="ayuntamiento", inversion_type="gold"),
    Inversion(concept="campamento", inversion_type="elixir"),
    Inversion(concept="cuartel", inversion_type="elixir"),
    Inversion(concept="laboratorio", inversion_type="elixir"),
    Inversion(concept="caldero de hechizos", inversion_type="elixir"),
    Inversion(concept="rey bárbaro", inversion_type="dark-elixir"),
    Inversion(concept="cuartel oscuro", inversion_type="elixir"),
    Inversion(concept="caldero de hechizos oscuro", inversion_type="elixir"),
    Inversion(concept="reina arquera", inversion_type="dark-elixir"),
    Inversion(concept="gran centinela", inversion_type="elixir"),
    Inversion(concept="taller", inversion_type="elixir"),
    Inversion(concept="luchadora real", inversion_type="dark-elixir"),
    Inversion(concept="recolector de elixir", inversion_type="gold"),
    Inversion(concept="almacén de elixir", inversion_type="gold"),
    Inversion(concept="mina de oro", inversion_type="elixir"),
    Inversion(concept="almacén de oro", inversion_type="elixir"),
    Inversion(concept="extractor de elixir oscuro", inversion_type="elixir"),
    Inversion(concept="almacén de elixir oscuro", inversion_type="elixir"),
    Inversion(concept="cañón", inversion_type="gold"),
    Inversion(concept="torre de arqueras", inversion_type="gold"),
    Inversion(concept="muro", inversion_type="walls"),
    Inversion(concept="mortero", inversion_type="gold"),
    Inversion(concept="cohetes de defensa", inversion_type="gold"),
    Inversion(concept="torre de mago", inversion_type="gold"),
    Inversion(concept="controlador aéreo", inversion_type="gold"),
    Inversion(concept="torre tesla", inversion_type="gold"),
    Inversion(concept="torre bombardera", inversion_type="gold"),
    Inversion(concept="ballesta", inversion_type="gold"),
    Inversion(concept="torre infernal", inversion_type="gold"),
    Inversion(concept="águila de artillería", inversion_type="gold"),
    Inversion(concept="catapulta", inversion_type="gold"),
    Inversion(concept="bomba", inversion_type="gold"),
    Inversion(concept="trampa con muelle", inversion_type="gold"),
    Inversion(concept="bomba aérea", inversion_type="gold"),
    Inversion(concept="conjunto de explosivos", inversion_type="gold"),
    Inversion(concept="mina de rastreo aérea", inversion_type="gold"),
    Inversion(concept="trampa de esqueletos", inversion_type="gold"),
    Inversion(concept="trampa tornado", inversion_type="gold"),
    Inversion(concept="inv. bárbaro", inversion_type="elixir"),
    Inversion(concept="inv. arquera", inversion_type="elixir"),
    Inversion(concept="inv. gigante", inversion_type="elixir"),
    Inversion(concept="inv. duende", inversion_type="elixir"),
    Inversion(concept="inv. rompemuros", inversion_type="elixir"),
    Inversion(concept="inv. globo bombástico", inversion_type="elixir"),
    Inversion(concept="inv. mago", inversion_type="elixir"),
    Inversion(concept="inv. curandera", inversion_type="elixir"),
    Inversion(concept="inv. dragón", inversion_type="elixir"),
    Inversion(concept="inv. pekka", inversion_type="elixir"),
    Inversion(concept="inv. bebé dragón", inversion_type="elixir"),
    Inversion(concept="inv. minero", inversion_type="elixir"),
    Inversion(concept="inv. dragón eléctrico", inversion_type="elixir"),
    Inversion(concept="inv. yeti", inversion_type="elixir"),
    Inversion(concept="inv. hechizo de rayo", inversion_type="elixir"),
    Inversion(concept="inv. hechizo curativo", inversion_type="elixir"),
    Inversion(concept="inv. hechizo de furia", inversion_type="elixir"),
    Inversion(concept="inv. hechizo de salto", inversion_type="elixir"),
    Inversion(concept="inv. hechizo de hielo", inversion_type="elixir"),
    Inversion(concept="inv. hechizo de clonación", inversion_type="elixir"),
    Inversion(concept="inv. hechizo de veneno", inversion_type="dark-elixir"),
    Inversion(concept="inv. hechizo de terremoto", inversion_type="dark-elixir"),
    Inversion(concept="inv. hechizo de aceleración", inversion_type="dark-elixir"),
    Inversion(concept="inv. hechizo de esqueletos", inversion_type="dark-elixir"),
    Inversion(concept="inv. hechizo de murciélago", inversion_type="dark-elixir"),
    Inversion(concept="inv. esbirro", inversion_type="dark-elixir"),
    Inversion(concept="inv. montapuercos", inversion_type="dark-elixir"),
    Inversion(concept="inv. valquiria", inversion_type="dark-elixir"),
    Inversion(concept="inv. gólem", inversion_type="dark-elixir"),
    Inversion(concept="inv. bruja", inversion_type="dark-elixir"),
    Inversion(concept="inv. sabueso de lava", inversion_type="dark-elixir"),
    Inversion(concept="inv. lanzarrocas", inversion_type="dark-elixir"),
    Inversion(concept="inv. gólem de hielo", inversion_type="dark-elixir"),
    Inversion(concept="inv. cazadora de héroes", inversion_type="dark-elixir"),
    Inversion(concept="inv. destrozamuros", inversion_type="elixir"),
    Inversion(concept="inv. dirigible bélico", inversion_type="elixir"),
    Inversion(concept="inv. arrojapiedras", inversion_type="elixir"),
    Inversion(concept="inv. cuartel de asedio", inversion_type="elixir"),
]

manager = InversionManager(inversions=_inversions)
